services:
  dns-server-secondary-01:
    container_name: dns-server-secondary-01
    hostname: dns-server-secondary-01
    build:
      context: .
      dockerfile: Dockerfile
    image: ducfuc/dns-server:source
    ports:
      - "15380:5380/tcp"
      - "15344:53443/tcp"
    environment:
      - DNS_SERVER_DOMAIN=dns-server-secondary-01
      - DNS_SERVER_LOG_FOLDER_PATH=/var/log/technitium/dns
    volumes:
      - secondary-config:/etc/dns
      - secondary-logs:/var/log/technitium/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
    networks:
      - dns_cluster

volumes:
  secondary-config:
  secondary-logs:

networks:
  dns_cluster:
    name: dns_cluster
    external: true
