services:
  dns-server-primary:
    container_name: dns-server-primary
    hostname: dns-server-primary
    build:
      context: .
      dockerfile: Dockerfile
    image: ducfuc/dns-server:source
    ports:
      - "5380:5380/tcp" #DNS web console (HTTP)
      - "53443:53443/tcp" #DNS web console (HTTPS)
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
      - "853:853/udp" #DNS-over-QUIC service
      - "853:853/tcp" #DNS-over-TLS service
      - "443:443/udp" #DNS-over-HTTPS service (HTTP/3)
      - "443:443/tcp" #DNS-over-HTTPS service (HTTP/1.1, HTTP/2)
      - "80:80/tcp" #DNS-over-HTTP service
      - "8053:8053/tcp" #DNS-over-HTTP service
      - "67:67/udp" #DHCP service
    environment:
      - DNS_SERVER_DOMAIN=dns-server-primary
    volumes:
      - primary-config:/etc/dns
      - primary-logs:/var/log/technitium/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
    networks:
      - dns_cluster

  dns-tester:
    container_name: dns-tester
    image: nicolaka/netshoot
    command: tail -f /dev/null
    networks:
      - dns_cluster
    restart: unless-stopped

volumes:
  primary-config:
  primary-logs:

networks:
  dns_cluster:
    name: dns_cluster
    driver: bridge
